<?php
/*
O FORMULÁRIO PODE SER ENVIADO COM DOIS TIPOS DE METHOD
1 - POST -> ENVIA A INFORMAÇÃO DE FORMA OCULTA
2 - GET  -> ENVIA A INFORMAÇÃO DE FORMA PÚBLICA, PELA URL

PARA RECEBER AS INFORMAÇÕES ENVIADAS PELO FORMULÁRIO, USAREMOS UMA VARIÁVEL SUPER GLOBAL. O MÉTODO ADOTADO NO FORM DEFINIRÁ A SUPERGLOBAL USADA AQUI
POST -> $_POST["NAME DO IMPUT QUE VC QUER"]
GET  -> $_GET["NAME DO IMPUT QUE VC QUER"]
*/


    //RECEBO OS VALORES DO FORM E ATRIBUO PARA UMA VARIÁVEL
    $nome = $_POST["nome"];
    $email = $_POST["mail"];

    //IMPRESSÃO DAS VARIÁVEIS NA TELA DO USUÁRIO
    echo "Seu nome é: " . $nome;
    echo "<br>";
    echo "Seu e-mail é: " . $email;

?>